package com.example.worktimeoff.controller;

import com.example.worktimeoff.dto.TimeOffRequestDTO;
import com.example.worktimeoff.model.User;
import com.example.worktimeoff.service.TimeOffService;
import com.example.worktimeoff.service.UserService;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.element.Cell;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.io.ByteArrayOutputStream;
import java.security.Principal;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Collectors;

@RestController
@RequestMapping("/api/reports")
public class ReportController {

    private final TimeOffService timeOffService;
    private final UserService userService;

    public ReportController(TimeOffService timeOffService, UserService userService) {
        this.timeOffService = timeOffService;
        this.userService = userService;
    }

    @GetMapping("/pdf")
    public ResponseEntity<?> generateReport(
            @RequestParam @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate startDate,
            @RequestParam @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate endDate,
            Principal principal) {
        if (principal == null) return ResponseEntity.status(HttpStatus.UNAUTHORIZED).build();
        User u = userService.findByEmail(principal.getName()).orElseThrow();

        if (!"MANAGER".equalsIgnoreCase(u.getRole()) && !"ADMIN".equalsIgnoreCase(u.getRole())) {
            return ResponseEntity.status(HttpStatus.FORBIDDEN).body(Map.of("error", "Only managers and admins can generate reports"));
        }

        try {
            List<TimeOffRequestDTO> requests;
            
            if ("ADMIN".equalsIgnoreCase(u.getRole())) {
                // Admin sees all requests
                requests = timeOffService.listAllRequests(Optional.of("APPROVED"));
            } else {
                // Manager sees only team requests
                requests = timeOffService.listForManager(u.getId(), Optional.of("APPROVED"));
            }
            
            // Filter by date range
            requests = requests.stream()
                .filter(r -> !r.getStartDate().isBefore(startDate) && !r.getEndDate().isAfter(endDate))
                .collect(Collectors.toList());

            ByteArrayOutputStream pdfBuffer = new ByteArrayOutputStream();
            PdfWriter writer = new PdfWriter(pdfBuffer);
            Document doc = new Document(new com.itextpdf.kernel.pdf.PdfDocument(writer));

            // Title
            doc.add(new Paragraph("Time Off Report")
                .setFontSize(18)
                .setBold());
            doc.add(new Paragraph("Period: " + startDate + " to " + endDate));
            doc.add(new Paragraph("Generated by: " + u.getFullName())
                .setMarginBottom(20));

            // Table
            Table table = new Table(7);
            table.addHeaderCell(new Cell().add(new Paragraph("Employee Name")));
            table.addHeaderCell(new Cell().add(new Paragraph("Type")));
            table.addHeaderCell(new Cell().add(new Paragraph("Start Date")));
            table.addHeaderCell(new Cell().add(new Paragraph("End Date")));
            table.addHeaderCell(new Cell().add(new Paragraph("Status")));
            table.addHeaderCell(new Cell().add(new Paragraph("Approved By")));
            table.addHeaderCell(new Cell().add(new Paragraph("Comment")));

            for (TimeOffRequestDTO request : requests) {
                table.addCell(new Cell().add(new Paragraph(request.getUserName())));
                table.addCell(new Cell().add(new Paragraph(request.getType())));
                table.addCell(new Cell().add(new Paragraph(request.getStartDate().toString())));
                table.addCell(new Cell().add(new Paragraph(request.getEndDate().toString())));
                table.addCell(new Cell().add(new Paragraph(request.getStatus())));
                table.addCell(new Cell().add(new Paragraph(request.getReviewedByName() != null ? request.getReviewedByName() : "N/A")));
                table.addCell(new Cell().add(new Paragraph(request.getManagerComment() != null ? request.getManagerComment() : "")));
            }

            doc.add(table);
            doc.close();

            byte[] pdfBytes = pdfBuffer.toByteArray();

            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_PDF);
            headers.setContentDispositionFormData("attachment", "timeoff-report.pdf");
            headers.setContentLength(pdfBytes.length);

            return new ResponseEntity<>(pdfBytes, headers, HttpStatus.OK);

        } catch (Exception e) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                .body(Map.of("error", "Failed to generate PDF: " + e.getMessage()));
        }
    }

    @GetMapping("/data")
    public ResponseEntity<?> getReportData(
            @RequestParam @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate startDate,
            @RequestParam @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate endDate,
            @RequestParam List<String> status,
            Principal principal) {
        if (principal == null) return ResponseEntity.status(HttpStatus.UNAUTHORIZED).build();
        User u = userService.findByEmail(principal.getName()).orElseThrow();

        if (!"MANAGER".equalsIgnoreCase(u.getRole()) && !"ADMIN".equalsIgnoreCase(u.getRole())) {
            return ResponseEntity.status(HttpStatus.FORBIDDEN).body(Map.of("error", "Only managers and admins can view reports"));
        }

        List<TimeOffRequestDTO> requests;
        if ("ADMIN".equalsIgnoreCase(u.getRole())) {
            requests = timeOffService.listAllRequests(Optional.empty());
        } else {
            requests = timeOffService.listForManager(u.getId(), Optional.empty());
        }

        List<String> upperStatuses = status.stream().map(String::toUpperCase).collect(Collectors.toList());
        requests = requests.stream()
            .filter(r -> upperStatuses.contains(r.getStatus().toUpperCase()))
            .filter(r -> !r.getStartDate().isBefore(startDate) && !r.getEndDate().isAfter(endDate))
            .collect(Collectors.toList());

        return ResponseEntity.ok(requests);
    }
}
